version: "3.3"

services:
  web_service:
    image: github-project_gabrielcarneirodeveloper:1
    ports:
      - 3333:3333
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - libquality
    depends_on: 
      - mongo
