version: "3.8"

services:
  web_service:
    image: github-project_gabrielcarneirodeveloper:1
    ports:
      - 3333:3333
    environment:
      - NODE_ENV=production
    deploy:
      mode: replicated
      replicas: 2

  mongo:
    image: mongo
    deploy:
      restart_policy:
        condition: on-failure
    environment:
        - MONGO_INITDB_DB=libquality
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=senha123
    ports:
      - 5558:27017
    volumes:
      - mongodb-volume:/data/db
    command: --auth

volumes:
  mongodb-volume: