version: "3.3"

services:
  web_service:
    image: libquality_gabrielcarneirodeveloper:1
    ports:
      - ${PORT}:3333
    deploy:
      mode: replicated
      replicas: 1
    env_file: ./deploy.prop
    environment: 
      - DB_HOST=""
      - ELK_HOST=""
    