version: '3'

services:

  mongo:
    image: mongo
    deploy:
      restart_policy:
        condition: on-failure
    environment:
        - MONGO_INITDB_DATABASE=$DB_DATABASE
        - MONGO_INITDB_ROOT_USERNAME=$DB_ROOT_USER
        - MONGO_INITDB_ROOT_PASSWORD=$DB_ROOT_PASS
        - MONGO_INITDB_USERNAME=$DB_USER
        - MONGO_INITDB_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_PORT:27017
    volumes:
      - mongodb-volume:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    command: --auth

volumes:
  mongodb-volume:
